# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    increment_version_number(
      version_number: "1.0.0"
    )
    build_app(
      workspace: "Runner.xcworkspace", 
      scheme: "Runner", 
      export_method: "app-store",
      clean: true,
      silent: true, 
      #xcargs: "-allowProvisioningUpdates"
    )
    upload_to_app_store(
      force: true,
      skip_screenshots: true, 
      skip_metadata: true,
      precheck_include_in_app_purchases: false,
      copyright: '2021 SUPLO VIETNAM .,JSC'
    )
  end
end
